///////////////////////////////////////////////////////////
//  EventManager.cs
//  Implementation of the Class EventManager
//  Generated by Enterprise Architect
//  Created on:      04-8ÔÂ-2017 16:59:16
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using GameFramework.Event;
namespace GameFramework.Event {
	public class EventManager : IEventManager, GameFrameworkModule, IEventManager {

		public GameFramework.Event.EventPool m_EventPool;

		public EventManager(){

		}

		~EventManager(){

		}

		public int Update(){

			return 0;
		}

		public int Subscribe(){

			return 0;
		}

		public int Fire(){

			return 0;
		}

	}//end EventManager

}//end namespace GameFramework.Event