///////////////////////////////////////////////////////////
//  EventComponent.cs
//  Implementation of the Class EventComponent
//  Generated by Enterprise Architect
//  Created on:      04-8ÔÂ-2017 16:59:16
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using GameFramework.Event;
namespace GameFramework.Event {
	public class EventComponent {

		private int IEventManager;
		public GameFramework.Event.IEventManager m_IEventManager;

		public EventComponent(){

		}

		~EventComponent(){

		}

		public int Awake(){

			return 0;
		}

		public int Subscribe(){

			return 0;
		}

		public int Fire(){

			return 0;
		}

	}//end EventComponent

}//end namespace GameFramework.Event