///////////////////////////////////////////////////////////
//  IEventManager.cs
//  Implementation of the Interface IEventManager
//  Generated by Enterprise Architect
//  Created on:      04-8ÔÂ-2017 16:59:17
//  Original author: Administrator
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace GameFramework.Event {
	public interface IEventManager  {

		int Subscribe();

		int Fire();
	}//end IEventManager

}//end namespace GameFramework.Event